apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: app
        color: blue
    spec:
      containers:
      - name: blue-app
        image: devopsnexus/bg-app
        imagePullPolicy: Never
