apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        color: green
    spec:
      containers:
      - name: green-app
        image: devopsnexus/bg-app
        imagePullPolicy: IfNotPresent
